[server]
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = true

[runner]
fastReruns = true

[logger]
level = "info"

[theme]
base = "dark"  # Changed from "light" to "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#1E1E1E"  # Darker secondary background
textColor = "#FAFAFA"  # Light text for better contrast
font = "sans serif"